### ISSUE TITLE
Генерация значений ENUM и вложенных объектов в Request Body

### ISSUE THREAD

**Issue by Dmitryitis** [Sheventon/postman-generator#12]
В текущей реализации в методах POST и PUT, которые имеют принимают на вход тело запроса, нет автоматической генерации значений полей типа ENUM. Присутствует заполнение вложенных объектов, но только на 1 уровень в глубиину. Предлагается добавить заполение ENUM и вложенных объектов более чем на 1 уровень в глубину.

**Comment by Sheventon** [comment]
Спасибо за предложение, данный функционал довольно полезный, можно его добавлять

**Comment by Dmitryitis** [comment]
https://github.com/Sheventon/postman-generator/pull/13

**Comment by Sheventon** [comment]
> #13

Спасибо за вклад в данный проект и за улучшение функционала
